# render.yaml
# Render Blueprint for automatic deployment

services:
  - type: web
    name: llm-deployment-system
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SHARED_SECRET
        sync: false
      - key: AIPIPE_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health
